Repository pywbem/pywbemtools, pull requests merged in 2019-07, with the labels that each got.

#180 Add tests for the class command.
  docs/pywbemclicmdshelp.rst
  pywbemcli/_cmd_class.py
  tests/unit/simple_mock_model_ext.mof
  tests/unit/test_class_subcmd.py
  tests/unit/test_pywbemclicmds.py.save
Labels: area: code, area: test

#181 Add tests for server subcommand
  docs/pywbemclicmdshelp.rst
  pywbemcli/_cmd_server.py
  pywbemcli/_pywbem_server.py
  pywbemcli/_pywbemcli_operations.py
  tests/schema/OpenPegasus/PG_Namespace.mof
  tests/schema/cim_schema_2.49.0Final-MOFs.zip
  tests/unit/test_server_subcmd.py
  tests/unit/utils/dmtf_mof_schema_def.py
  tests/unit/utils/wbemserver_mock.py
Labels: area: code, area: test

#186 Remove superflous debug file.
  pywbemcli/_debugtools.py
Labels: area: test, release: mandatory

#190 Added some missing tests to server tests and instance tests
  pywbemcli/_cmd_instance.py
  pywbemcli/_cmd_server.py
  pywbemcli/_context_obj.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_server_subcmd.py
Labels: review needed

#201 Modify options for connection add
  docs/pywbemclicmdshelp.rst
  pywbemcli/_cmd_connection.py
  tests/unit/test_connection_subcmd.py
Labels: review needed

#198 Fixes # 188 Modify table output formats to match other project
  docs/pywbemclicmdshelp.rst
  pywbemcli/_common.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_global_options.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_server_subcmd.py
  tests/unit/test_tableformat.py
Labels: review needed

#204 Extend the general help messages to:
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/test_global_options.py
Labels: review needed

#195 Ks/fix readme. rst
  README.rst
Labels: review needed

#207 Change the search algorithm for the class find command from regex
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_common.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#208 Fixed package name in setup.cfg
  setup.cfg
Labels: area: setup, priority, type: bug

#214 Ks/add filter query
  docs/pywbemclicmdshelp.rst
Labels: review needed

#203 Remove includequalifiers option on associators/references
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_common_options.py
  pywbemtools/pywbemcli/_context_obj.py
  tests/unit/cli_test_extensions.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#216 Modify connection table formatting
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_cmd_connection.py
  pywbemtools/pywbemcli/_common.py
  tests/unit/test_common.py
  tests/unit/test_connection_subcmd.py
Labels: review needed

#217 Clean up a number of pylint messages and change the word global to
  pywbemtools/pywbemcli/__init__.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_cmd_qualifier.py
  pywbemtools/pywbemcli/_context_obj.py
  pywbemtools/pywbemcli/_version.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/live_unit/test_pegasus.py
  tests/unit/cli_test_extensions.py
  tests/unit/mock_prompt_0.py
  tests/unit/pytest_extensions.py
  tests/unit/simple_mock_invokemethod.py
  tests/unit/simple_python_mock_script.py
  tests/unit/test_common.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_pywbem_server.py
  tests/unit/utils/wbemserver_mock.py
Labels: review needed

#218 Ks/fix filterquery
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/test_global_options.py
  tests/unit/test_instance_subcmd.py
Labels: rebase needed, update needed
