Repository pywbem/pywbemtools, pull requests merged in 2019-08, with the labels that each got.

#222 Modify one --names_only option
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_common_options.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#223 Added tests to improve coverage.
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_cmd_connection.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_common.py
  tests/unit/mock_confirm_n.py
  tests/unit/test_common.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#230 Fix issues in passing MaxObjCnt to the operations.
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_global_options.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#235 Fix issue #231 unhandled exception on startup (alternate solution to pr # 233
  pywbemtools/pywbemcli/_cmd_connection.py
  pywbemtools/pywbemcli/_common.py
  pywbemtools/pywbemcli/_context_obj.py
  pywbemtools/pywbemcli/_pywbem_server.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/mock_confirm_n.py
  tests/unit/mock_confirm_y.py
  tests/unit/mock_prompt_0.py
  tests/unit/test_common.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_global_options.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#234 Fix issue #192 - exception for cmd pywbemcli c
  requirements.txt
Labels: review needed

#238 Change name of live_unit directory to to manual
  tests/manual/test_pegasus.py
  tests/unit/test_general_options.py
Labels: review needed

#268 Issue # 264 - click_help_capture fails on windows
  tools/click_help_capture.py
Labels: update needed

#262 Fixes #248: Use of --output-format general option
  docs/pywbemclicmdshelp.rst
  docs/pywbemcligeneraloptions.rst
  docs/pywbemclisubcommands.rst
  pywbemtools/pywbemcli/_common.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_general_options.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_qualdecl_subcmd.py
Labels: review needed

#270 Fixed dependencies of generated help docs file
  Makefile
Labels: area: devlopment env, type: bug

#272 Fixes #248: Updated description of output formats
  docs/pywbemcligeneraloptions.rst
Labels: area: docs

#276 Updated command descriptions
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_cmd_connection.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_cmd_qualifier.py
  pywbemtools/pywbemcli/_cmd_server.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_qualdecl_subcmd.py
  tests/unit/test_server_subcmd.py
Labels: area: docs, type: enhancement

#280 Fixes issue #271 error with class enumerate
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_common.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#293 Removed display of mock repository with --verbose
  pywbemtools/pywbemcli/_pywbemcli_operations.py
Labels: area: code, type: enhancement

#296 Removed Makefile in docs
  docs/Makefile
Labels: area: devlopment env, type: cleanup
