Repository pywbem/pywbemtools, pull requests merged in 2019-09, with the labels that each got.

#302 Docs: Fixed Sphinx build warnings, broken links, typos
  docs/pywbemclicmdlineinterface.rst
  docs/pywbemcligeneraloptions.rst
Labels: area: docs, type: bug

#303 Fixes #282: Added section for specifying INSTANCENAME
  docs/pywbemclicommands.rst
Labels: review needed

#308 fixes issue # 298, MaxObjectCnt failure on window
  pywbemtools/pywbemcli/pywbemcli.py
Labels: review needed

#318 Added .pytest_cache to make clean
  Makefile
Labels: area: devlopment env, type: enhancement

#311 Updated help text of repl command and help
  pywbemtools/pywbemcli/pywbemcli.py
Labels: area: code, type: enhancement

#312 Fixed help file dependency in make build
  Makefile
Labels: area: devlopment env, type: bug

#310 Ks/#250 replace short options
  docs/pywbemclicmdshelp.rst
  docs/pywbemclicommands.rst
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_cmd_server.py
  pywbemtools/pywbemcli/_common_options.py
  tests/unit/common_options_help_lines.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_instance_subcmd.py
  tests/unit/test_server_subcmd.py
Labels: review needed

#326 Correct an issue found in invokemethod with array parameters.
  docs/pywbemclicommands.rst
  pywbemtools/pywbemcli/_common.py
  tests/unit/all_types.mof
  tests/unit/all_types_method_mock.py
  tests/unit/simple_mock_invokemethod.py
  tests/unit/test_class_subcmd.py
  tests/unit/test_instance_subcmd.py
Labels: review needed

#320 Fixes #297: Updated README and README_PYPI
  README.rst
  README_PYPI.rst
  docs/introduction.rst
Labels: discussion needed

#336 Fixes #335 #338: Modify so general opts work in interactive mode
  docs/appendix.rst
  docs/pywbemclicmdshelp.rst
  docs/pywbemclicommands.rst
  docs/pywbemcligeneraloptions.rst
  pywbemtools/pywbemcli/_cmd_connection.py
  pywbemtools/pywbemcli/_context_obj.py
  pywbemtools/pywbemcli/_pywbem_server.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/cli_test_extensions.py
  tests/unit/test_connection_subcmd.py
  tests/unit/test_general_options.py
  tests/unit/test_pywbem_server.py
  tests/unit/utils.py
Labels: review needed

#372 Fixes issue # 358 Fix instance count command
  docs/pywbemclicmdshelp.rst
  docs/pywbemclicommands.rst
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_cmd_instance.py
  pywbemtools/pywbemcli/_common.py
  pywbemtools/pywbemcli/_common_options.py
  tests/unit/common_options_help_lines.py
  tests/unit/simple_assoc_mock_model.mof
  tests/unit/simple_mock_model_ext.mof
  tests/unit/test_class_cmds.py
  tests/unit/test_instance_cmds.py
Labels: review needed

#382 Allow turning off --verbose in interactive mode
  docs/pywbemclicmdshelp.rst
  pywbemtools/pywbemcli/_context_obj.py
  pywbemtools/pywbemcli/pywbemcli.py
  tests/unit/cli_test_extensions.py
  tests/unit/test_general_options.py
  tests/unit/utils.py
Labels: review needed

#398 Fixes issue #397, mask password on connection show display
  pywbemtools/pywbemcli/_cmd_connection.py
  tests/unit/test_connection_cmds.py
  tests/unit/test_general_options.py
Labels: review needed

#412 Fixes issue #410, executing tests in verbose mode
  tests/unit/test_connection_cmds.py
  tests/unit/test_general_options.py
Labels: review needed

#418 Travis: Fixed coveralls to run again for py34/latest
  .travis.yml
Labels: roll back/forward done
