Repository pywbem/pywbemtools, pull requests merged in 2020-03, with the labels that each got.

#486 pick_from_list bypass user request if only one choice
  docs/pywbemcli/cmdshelp.rst
  docs/pywbemcli/commands.rst
  docs/pywbemcli/features.rst
  pywbemtools/pywbemcli/_common.py
  tests/unit/test_common.py
  tests/unit/test_connection_cmds.py
Labels: review needed

#499 Accomodated Click 7.1.1 error messages; Improved assertion messages
  docs/changes.rst
  requirements.txt
  tests/unit/cli_test_extensions.py
  tests/unit/test_class_cmds.py
  tests/unit/utils.py
Labels: priority

#522 0.5: Pinned Pygments to <2.4.0 and readme-renderer to <25.0 for Python 3.4
  dev-requirements.txt
  docs/changes.rst
Labels: priority

#520 Fixes #521: Pinned Pygments to <2.4.0 and readme-renderer to <25.0 for Python 3.4
  dev-requirements.txt
  docs/changes.rst
Labels: priority, roll back/forward done

#515 Fixes #489: Use of pywbem internal functions
  docs/changes.rst
  minimum-constraints.txt
  pywbemtools/pywbemcli/__init__.py
  pywbemtools/pywbemcli/_association_shrub.py
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_common.py
  pywbemtools/pywbemcli/_displaytree.py
  pywbemtools/pywbemcli/_utils.py
  requirements.txt
  tests/unit/test_class_cmds.py
  tests/unit/test_common.py
Labels: review needed

#527 Fixes #489: Second part of changes to remove pywbem dependence
  pywbemtools/pywbemcli/__init__.py
  pywbemtools/pywbemcli/_cimvalueformatter.py
  pywbemtools/pywbemcli/_common.py
Labels: review needed

#535 Fixed incorrect minimum version of functools32
  minimum-constraints.txt
Labels: priority, roll back/forward done

#543 Fixes issue # 537 Hide the text output from a number of tests.
  tests/unit/test_common.py
  tests/unit/test_general_options.py
Labels: review needed

#545 Pinned dparse to <0.5.0 on py27 due to an issue
  dev-requirements.txt
  docs/changes.rst
Labels: roll back/forward done

#552 Fixes #553: Fixed invalid test validation; minor test cleanup
  docs/changes.rst
  tests/unit/cli_test_extensions.py
  tests/unit/test_class_cmds.py
  tests/unit/test_connection_cmds.py
  tests/unit/test_instance_cmds.py
  tests/unit/test_qualdecl_cmds.py
Labels: priority
