Repository pywbem/pywbemtools, pull requests merged in 2021-05, with the labels that each got.

#958 Fixes issue# 935, Confusing exception display from server add_mof and remove_mof()
  docs/changes.rst
  pywbemtools/pywbemcli/_cmd_server.py
  tests/unit/test_server_cmds.py
Labels: review needed

#972 Extended the pinning of Click to <8.0.0 to dev-requirements.txt
  dev-requirements.txt
  requirements.txt
Labels: roll back/forward done

#984 Moved validate_required_arg() to common _options.py module
  pywbemtools/_options.py
  pywbemtools/pywbemcli/_cmd_instance.py
Labels: priority

#985 Generalized test command execution to be common across commands
  tests/end2endtest/test_errors.py
  tests/end2endtest/test_server.py
  tests/unit/pywbemcli/cli_test_extensions.py
  tests/unit/utils.py
Labels: priority
