Repository pywbem/pywbemtools, pull requests merged in 2021-01, with the labels that each got.

#840 Removed use of pywbem_os_setup script for install
  Makefile
Labels: roll back/forward done

#842 In normal test envs, added py27 and removed minimum levels on Win/macOS
  .github/workflows/test.yml
Labels: roll back/forward done

#849 Fixed change log by adding GitHub Actions change
  docs/changes.rst
Labels: roll back/forward done

#869 fixes issue #387 Fixes tests tied to stdin
  docs/changes.rst
  tests/unit/test_instance_cmds.py
Labels: review needed

#880 Showing compiled objects when creating a mock environment in verbose mode
  docs/changes.rst
  pywbemtools/pywbemcli/_pywbemcli_operations.py
  tests/unit/test_general_options.py
  tests/unit/test_misc_errors.py
  tests/unit/test_pywbemcli_operations.py
  tests/unit/test_tableformat.py
  tests/unit/utils.py
Labels: priority

#876 Fixes #682: Add more filter options
  docs/pywbemcli/cmdshelp.rst
  docs/pywbemcli/commands.rst
  docs/pywbemcli/generaloptions.rst
  pywbemtools/pywbemcli/_cmd_class.py
  pywbemtools/pywbemcli/_common.py
  pywbemtools/pywbemcli/_common_options.py
  pywbemtools/pywbemcli/_displaytree.py
  tests/unit/common_options_help_lines.py
  tests/unit/qualifier_filter_model.mof
  tests/unit/test_class_cmds.py
  tests/unit/test_common.py
  tests/unit/test_instance_cmds.py
Labels: review needed
