Repository pywbem/pywbemtools, pull requests merged in 2023-01, with the labels that each got.

#1262 Fixed missing astroid requirement on typing-extensions
  dev-requirements.txt
  minimum-constraints.txt
Labels: waiting

#1261 Fixed docutils requirement in dev-requirements.txt
  dev-requirements.txt
Labels: waiting

#1264 Ks/jan2023 new security issues.
  Makefile
  dev-requirements.txt
  docs/changes.rst
  minimum-constraints.txt
  requirements.txt
Labels: priority

#1260 Fix issue with instance table column ordering
  docs/changes.rst
  pywbemtools/pywbemcli/_cmd_instance.py
  tests/unit/pywbemcli/test_instance_cmds.py
Labels: type: bug, review needed

#1265 Fix issue where --pl option rtns error with poor explanation.
  docs/changes.rst
  pywbemtools/pywbemcli/_common.py
  tests/unit/pywbemcli/test_common.py
Labels: area: code, review needed, type: cleanup

#1266 Fix issue where output is error code rather than error code string
  docs/changes.rst
  docs/pywbemcli/commands.rst
  pywbemtools/pywbemcli/_cmd_instance.py
  tests/end2endtest/test_instance_count.py
Labels: review needed, type: cleanup
